### ISSUE TITLE
Release v2.12.12 checklist

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#487]
- [x] update internal nodes
- [x] update hosted nodes
       - [ ] 050 second brain node (doesn't need relay but still track)   
- [x] open PR for update on Umbrel
- [x] inform home node users on telegram channel
- [x] update proxy1 node
- [x] update proxy2 node
- [x] check lnd ver gameb_1
- [x] check lnd ver gameb_2

**Comment by pitoi** [comment]
let's list out each routing node and each proxy
I believe we also should add a line for the 2nd brain lsat related node just in case we move it to a diff server later we don't lose track of it as a special case

**Comment by kevkevinpal** [comment]
Umbrel PR
https://github.com/getumbrel/umbrel-apps/pull/275

**Comment by kevkevinpal** [comment]
This is finished
