### ISSUE TITLE
Release v2.12.13 checklist

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#599]
- [x] update internal nodes
- [x] update hosted nodes
       - [ ] 050 second brain node (doesn't need relay but still track)
- [x] update my personal Umbrel Node
- [x] open PR for update on Umbrel
- [x] inform home node users on telegram channel
- [x] update proxy1 node
- [x] update proxy2 node

**Comment by kevkevinpal** [comment]
created a new release

https://github.com/stakwork/sphinx-relay/releases/tag/v2.2.13

**Comment by kevkevinpal** [comment]
updated proxy node 2

**Comment by kevkevinpal** [comment]
New release on Umbrel
https://github.com/getumbrel/umbrel-apps/pull/404

**Comment by kevkevinpal** [comment]
cluster 050 updated will continue to update the clusters

**Comment by kevkevinpal** [comment]
All the above tasks are finished!
